apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: app
        image: {{.Values.image.repository}}:{{.Values.image.tag}}
        ports:
        - containerPort: 8080
